### ISSUE TITLE
Custom hotspot navigation icons

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/desipano#2]
The default up-arrow icon is confusing when some hotspots "go back" while others "go deeper".

Next steps:
- [x] How customizable are these icons?
- [x] What should they be?

**Comment by dkirkby** [comment]
I can customize the icon by adding the following scene hotspot argument:
```
  "cssClass": "nav-hotspot move-icon"
```
with corresponding CSS:
```
    .nav-hotspot {
        height: 48px;
        width: 48px;
        border: 4px solid #f00;
        border-radius: 8px;
        background-color: #fff;
        background-image: url(img/nav-icons.svg);
    }
    ...
    .move-icon {
        background-position: 0 -48px;
    }
```
For efficiency, use SVG icons and combine them into a single asset using `background-position` for indexing.

**Comment by dkirkby** [comment]
Here are the actual icons, contained in `docs/img/nav-icons.svg`:
<img width="50" alt="image" src="https://user-images.githubusercontent.com/185007/223147260-0af07919-28be-4d21-8057-b70ba7102a42.png">

**Comment by dkirkby** [comment]
I am using Google material icons from https://fonts.google.com/icons?icon.style=Rounded (with weight 700 and size 48 px)

**Comment by SamuelBrieden** [comment]
Very nice! 
Sometimes the popup of the Help button is displayed below the Move the robots button, which then covers part of the text. Maybe this can be handled by including "z-index" in the css?

**Comment by dkirkby** [comment]
Thanks, I will try to reproduce that so I can then experiment with z-index.

**Comment by dkirkby** [comment]
I was not able to reproduce text below an icon with chrome just now @SamuelBrieden:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/185007/224561136-b00b3a7e-e42c-4661-bf18-aadeabc2ed62.png">

Can you give a bit more details on what conditions led to this?

**Comment by SamuelBrieden** [comment]
Yes, I forgot to say I was using Safari. I confirm that this is not an issue in Chrome, but in Safari it is displayed as
<img width="603" alt="Screenshot 2023-03-13 at 10 45 55" src="https://user-images.githubusercontent.com/34127179/224681281-c90b0065-7892-4924-b87e-9121cc12b360.png">
I was using Safari, as Chrome gave me an error initially that it would not support WebGL. However, this can be fixed by ticking "Use hardware acceleration when available" in Chrome system preferences.

**Comment by dkirkby** [comment]
Thanks @SamuelBrieden.  I see now Safari on iOS has the same problem.

**Comment by dkirkby** [comment]
Ok, I think this is fixed now, for Mac + iOS Safari at least.
